# Generated by Django 3.2.5 on 2021-07-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210710_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
