# Generated by Django 3.2.5 on 2021-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(related_name='profiles', to='posts.Post'),
        ),
    ]
