# Generated by Django 3.2.5 on 2021-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210711_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(related_name='profiles', to='posts.Post'),
        ),
    ]
