# Generated by Django 3.2.5 on 2021-07-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='posts.post'),
            preserve_default=False,
        ),
    ]
