# Generated by Django 3.2.5 on 2021-07-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210711_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
